server:
  port: 8081

spring:
  application:
    name: dashboard-application-service
  datasource:
    url: jdbc:postgresql://localhost:5432/dashboard_db
    username: postgres
    password: test123
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  liquibase: #liquibase changelog properties
    enabled: true
    change-log: classpath:db/db-changelog-master.yaml
