server:
  port: 8080

spring:
  application:
    name: dashboard-application-service
  datasource:
#    url: jdbc:postgresql://localhost:5432/dashboard_db
    url: jdbc:postgresql://database-instance.cslzeauidjaw.ap-south-1.rds.amazonaws.com:5432/database_db_aws
    username: postgres
    password: postgres.123
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  liquibase: #liquibase changelog properties
    enabled: true
    change-log: classpath:db/db-changelog-master.yaml
  mail:
    host: smtp.gmail.com
    username: gauravsaubhagya3@gmail.com
    password: ssxvgmehukmvlmti
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: "*"
            protocols: TLSv1.2
